### ISSUE TITLE
unfreeze my avatar

### ISSUE THREAD

**Issue by tizu69** [Modern-Modpacks/website#3]
I am scared of the cold

@Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcat101  @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101 @Gcast101

**Comment by Gcat101** [comment]
![image](https://github.com/user-attachments/assets/17e3f26d-4707-445c-8106-372bee8457f1)

**Comment by tizu69** [comment]
ever thought about using the preferred pfp doe

**Comment by Gcat101** [comment]
your preferred pfp changes every 2 days

**Comment by tizu69** [comment]
nah, that's my discord pfp. preferred is actually the gh one, which I have updated to most but not all services by now (cuz I don't use them), discord one is just random shitposting

**Comment by tizu69** [comment]
any updates?

**Comment by Gcat101** [comment]
nope

**Comment by tizu69** [comment]
do updates
